name: smkdevapp
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.8
  http: ^0.12.1
  flushbar: ^1.10.4
  flutter_svg: ^0.19.1
  carousel_widget: ^0.1.1
  shimmer: ^1.1.2
  velocity_x: ^1.0.0
  image_picker: ^0.6.7+14
  firebase_storage: ^5.0.1
  flutter_speed_dial: ^1.2.5
  geolocator: ^5.3.2+2
  flutter_polyline_points: ^0.2.2
  google_maps_flutter: ^0.5.28+1
  fluttertoast: ^7.1.1
  webview_flutter: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
          - asset: assets/fonts/PoppinsBlack.ttf
          - asset: assets/fonts/PoppinsSemiBold.ttf
          - asset: assets/fonts/PoppinsBold.ttf
          - asset: assets/fonts/PoppinsExtraBold.ttf
          - asset: assets/fonts/PoppinsLight.ttf
          - asset: assets/fonts/PoppinsExtraLight.ttf
          - asset: assets/fonts/PoppinsMedium.ttf
          - asset: assets/fonts/PoppinsRegular.ttf
          - asset: assets/fonts/PoppinsThin.ttf